### PR TITLE
[KE,TZ,ZW] Afrobarometer Data

### PR DESCRIPTION
**Pull request by phillipahereza**
## Description

Add Afrobarometer Round 7 survey results for Kenya, Tanzania and Zimbabwe

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

screencapture-localhost-8000-profiles-region-5-iringa-2019-02-14-08_18_24-min
ke-min
zim-min

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — CHANGES_REQUESTED** [review]
:+1: @phillipahereza.

I've only tested it for Kenya but:

 1. `own_radio` has issues in KE
screenshot from 2019-02-18 14-27-58
 2. Afrobarometer should be in there in the Nav.
screenshot from 2019-02-18 14-28-35
 3. _Q41..._ should be removed
screenshot from 2019-02-18 14-30-00
 4. Sort from Strong disagree/Strong agree to Strong agree/Strong disagree.
screenshot from 2019-02-18 14-33-15

----------------------------------------

On code, I think it should be `Don't` here, check the encoding.
screenshot from 2019-02-18 14-34-23

**Review by kilemensi — CHANGES_REQUESTED** [review]
`own_radio` is still an issue @phillipahereza.

screenshot from 2019-02-22 10-53-23

**Comment by phillipahereza** [comment]
> `own_radio` is still an issue @phillipahereza.
> 
> screenshot from 2019-02-22 10-53-23

@kilemensi it's working fine for me, could you confirm that you're loading the data afresh

**Comment by kilemensi** [comment]
I'm running everything on Docker @phillipahereza so I expect it to be loading data afresh. But, let me even delete the local images and build from scratch.

**Comment by kilemensi** [comment]
> I'm running everything on Docker @phillipahereza so I expect it to be loading data afresh. But, let me even delete the local images and build from scratch.

Still fails @phillipahereza... Are you running it on docker or having a clean install?

**Comment by phillipahereza** [comment]
Good morning @kilemensi, Kenya fixed

**Comment by kilemensi** [comment]
> Good morning @kilemensi, Kenya fixed

Someone does not test their code on Docker/clean `env` before pushing.

**Review by kilemensi — APPROVED** [review]

**Review by kilemensi — CHANGES_REQUESTED** [review]
Oops, I think I jumped the gun there with my approval @phillipahereza ... Still not ready to merge
 1. Tanzania (and it's regions) still fail
screenshot from 2019-02-25 07-51-50

---------------------------------------------
Zimbabwe is :heavy_check_mark: though

**Review by kilemensi — APPROVED** [review]
:+1: @phillipahereza.

But create a story to deal with visual that have overflowing content like in this case.

screenshot from 2019-02-25 12-29-36

**Pull request merged**
