### PR TITLE
[ON HOLD] [Docker] Install command on dockerfile

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description
This PR enables python dependencies installation through Dockerfile

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by DavidLemayian — CHANGES_REQUESTED** [review]
Let's instead delete `requirements.txt` and use `codeforafrica/hurumap:0.0.15` docker image that has the right `hurumap` and `wazimap` (with releases) packages already installed.

We can though do this in future if there is a specific requirement that's missing from HURUmap-apps.

**Comment by KhadijaMahanga** [comment]
@DavidLemayian there're some requirements specific for the dominion project that need to be installed

**Comment by DavidLemayian** [comment]
@KhadijaMahanga Let's include those dependencies instead therefore so that we don't have the conflict of `wazimap` or `hurumap`.

**Comment by KhadijaMahanga** [comment]
Hi @DavidLemayian I have removed requirements.txt and updated the Hurumap docker image. But there is an ImportError that get's fixed with @phillipahereza 's PR. So we should merge this after Release v.0.1.0

**Comment by kilemensi** [comment]
Wazimap already supports API. We'll try to use the same approach and upgrade to DRF if and only if needed. Hence, no immediate need for extra dependencies.

**Pull request closed without merging**
