### PR TITLE
Add HURUmap Zambia files

### PR DESCRIPTION
**Pull request by malgamves**
This PR adds the HURUmap Zambia files here.

### CODE REVIEW

**Comment by malgamves** [comment]
Added the Zambia one as you asked

**Comment by DavidLemayian** [comment]
This is pretty awesome @malgamves. Thanks for taking time to contribute to HURUmap.

I've changed the base to develop because that's where we're doing majority of the development currently.

I can see a couple of "blank" files. What are they about?

**Comment by malgamves** [comment]
The blank files were just so I could create the directories. New to GitHub didn't know any other way . O ill push to develop now for my future commits.

**Comment by DavidLemayian** [comment]
Closing this because #27 is open.

**Pull request closed without merging**
