### PR TITLE
Add Afrobarometer Data for Uganda [161979054]

### PR DESCRIPTION
**Pull request by phillipahereza**
## Description

Add Afrobarometer data to HURUmap Uganda

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
screencapture-localhost-8000-profiles-region-115-eastern-uganda-2018-12-04-02_20_20

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
@phillipahereza good work. This is ready to go... *but*:

 1. Aren't we adding `Afrobarometer` as one of the headings?
 2. Is it too much work sorting responses from Strong agree to Strong disagree or vice versa? It's confusion to have: `Difficulty`, `Easy`, `Very Difficult`, etc.
 3. (Optional) Field table naming: either we use the spaces or not but lets have a standard.

PS: This is applicable to Zambia PR as well.

**Comment by phillipahereza** [comment]
> @phillipahereza good work. This is ready to go... _but_:
> 
> 1. Aren't we adding `Afrobarometer` as one of the headings?
> 2. Is it too much work sorting responses from Strong agree to Strong disagree or vice versa? It's confusion to have: `Difficulty`, `Easy`, `Very Difficult`, etc.
> 3. (Optional) Field table naming: either we use the spaces or not but lets have a standard.
> 
> PS: This is applicable to Zambia PR as well.

@kilemensi 
2. This might be a bit complicated coz almost every question has it's own responses, it has to be a manual process for all the visuals, but lemme give it a shot
3. We won't need fieldtables when we upgrade to Wazimap 2.0.0, so I don't think the naming is something we should be too concerned about

**Comment by phillipahereza** [comment]
@kilemensi fixed

**Comment by kilemensi** [comment]
> @kilemensi fixed

Works at *Provincial* level @phillipahereza but breaks whenever I go lower than that:

screenshot from 2018-12-05 08-14-46

I think it's the sorting function.

**Comment by kilemensi** [comment]
PS: Did you try the one viz per row using Histogram/Bar chart @phillipahereza? If you did and didn't like it, just include a screenshot here (or in any other PR) so that we can all see and **know** it doesn't work.

**Comment by phillipahereza** [comment]
> PS: Did you try the one viz per row using Histogram/Bar chart @phillipahereza? If you did and didn't like it, just include a screenshot here (or in any other PR) so that we can all see and **know** it doesn't work.

@kilemensi yes I tried the Histogram but personally, I didn't like it but here's a screenshot of what it looked like 
screenshot 2018-12-05 at 09 16 04

**Comment by kilemensi** [comment]
Any reason why you're concatenating the sort keys @phillipahereza? e.g.
```python
        internet_usage_key_order = mobile_phone_usage_key_order + ["Missing"]
```

Because it's hard to track and error prone. For example if you try visiting **Western Uganda**, you'll get key error: `u'Missing'` is missing for at least the following:

```python
        corruption_business_executives
        corruption_government_officials
        corruption_judges_and_magistrates
        corruption_local_government_councilors
        corruption_members_of_parliament
        corruption_office_of_the_presidency
        corruption_police
        corruption_religious_leaders
        corruption_traditional_leaders
        corruption_tax_officials
```

Anything using `corruption_amongst_key_order` basically.

**Comment by phillipahereza** [comment]
@kilemensi the keys for internet usage are similar those of mobile phone usage except `Missing`?
I think the quickest and safest solution would be to remove the `Missing` fields from the data

**Comment by kilemensi** [comment]
> @kilemensi the keys for internet usage are similar those of mobile phone usage except `Missing`?
> I think the quickest and safest solution would be to remove the `Missing` fields from the data

It may be the right solution *technically* @phillipahereza but is it a right solution *factually*? Isn't knowing there was 1 or 2 missing an important piece of information that will be lost if we just remove them?

**Comment by phillipahereza** [comment]
@kilemensi the fields with `Missing` refer to the fields that had no values or were blank, so I don't think removing them will have any effect

**Comment by kilemensi** [comment]
Oh, it is something **we** added.

If that's the case then yeah, go ahead and remove them @phillipahereza.

**Comment by phillipahereza** [comment]
@kilemensi I suspect the `Missing` was added as I was cleaning the data with pandas. I already adjusted 😎

**Pull request merged**
