### PR TITLE
Add Kenya Land Excisions data

### PR DESCRIPTION
**Pull request by phillipahereza**
## Description

Add data on the legality of land excisions in counties in Kenya

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
screencapture-localhost-9000-profiles-level1-KE_1_018-nyandarua-2019-03-25-06_56_08

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by phillipahereza** [comment]
@KhadijaMahanga the styling of the content in `profile_detail` is still ugly, tried putting it in a container but that too doesn't work. Could you help me style it, I think this should be done in React? Not sure though cc @kilemensi

**Comment by KhadijaMahanga** [comment]
> @KhadijaMahanga the styling of the content in `profile_detail` is still ugly, tried putting it in a container but that too doesn't work. Could you help me style it, I think this should be done in React? Not sure though cc @kilemensi

Hey @phillipahereza , I have done styling of the profile detail on my branch. So it will be merged. How about the charts color?

**Comment by phillipahereza** [comment]
@KhadijaMahanga the chart colors thing is a bit complicated but I'm making progress on it

**Review by KhadijaMahanga — COMMENTED** [review]
@phillipahereza did you dump fixtures to `dominion.json`. I can't seem to find the db table/fieldtable associated to the new table

**Pull request merged**
